api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import include 
from api import views

urlpatterns = [
        path('sensores/', views.SetNodeView.as_view()),
        path('sensores/<int:room_node>', views.GetNodeView.as_view()),
        path('sensores/<int:room_node>/all', views.GetNodeAllView.as_view())
]

# urlpatterns = format_suffix_patterns(urlpatterns)

entrena/urls.py
from django.urls import path
from entrena import views

app_name = 'entrena'

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('nodos/', views.NodeList.as_view(), name='lista_nodes'),
    path('habitaciones/', views.RoomList.as_view(), name='lista_rooms'),

    path('habitaciones/<int:pk>/nodos/', views.RoomNodeList.as_view(), name='lista_room_node'),
    path('habitaciones/<int:pk_room>/nodos/<str:pk_node>', views.RegNodeList.as_view(), name='lista_reg_node')
]

entrena_server/urls.py
from django.contrib import admin
from django.urls import path, include

# from api import views

# from rest_framework import routers

# router = routers.DefaultRouter()

# En el router vamos añadiendo los endpoints a los apiets
# router.register('registro/nodos', views.RegNodeViewSet)

urlpatterns = [

  #API url's
  # path('api/v1/', include(router.urls)),

  path('admin/', admin.site.urls),

  #entrena url's
  path('', include(('entrena.urls', 'vistas'), namespace='vistas')),
  
  path('api/v1/', include('api.urls')),

  # auth url's
  path('api/v1/auth/', include('rest_auth.urls')),
  path('api/v1/auth/registration/', include('rest_auth.registration.urls')),
]

api/models.py
from django.db import models

# Create your models here.

entrena/models.py
from django.db import models
import re
from django.urls import reverse


class Room(models.Model):
    nombre_hab = models.CharField("Nombre habitación",max_length=100, blank=False, unique=True)

    def __str__(self):
        return self.nombre_hab

    def get_absolute_url(self):
        return reverse('vistas:lista_rooms')
    
    class Meta():
        ordering = ['id']
        
class Node(models.Model):
    tipo_nodo = models.CharField("Tipo de nodo",max_length=100, blank=False)

    # ...
    """
    Adding a through option to the field will let Django know
    that it should use that model instead of creating one
    for you.
    """
    rooms = models.ManyToManyField(Room, through='Room_Node')

    def __str__(self):
        return self.tipo_nodo

    def get_absolute_url(self):
        return reverse('vistas:lista_nodes')

    class Meta:
        ordering = ['id']

class Room_Node(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    node = models.ForeignKey(Node, on_delete=models.CASCADE)

    class Meta():
        ordering = ['pk']

    # def save(self, *args, **kwargs):
    #     dig = re.sub("\D", "", self.room.nombre_hab)
    #     id_name = self.room.nombre_hab[:3] + dig
    #     id_name += self.node.tipo_nodo[:2]
    #     id_name += str(self.no_node)
        
    #     self.id_hab_nodo = id_name.upper()
        
    #     super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('vistas:lista_room_node', kwargs={ 'pk':self.room.pk })

class Reg_Node(models.Model):
    voltaje = models.FloatField("Voltaje",default=0.0)
    corriente = models.FloatField("Corriente",default=0.0)
    fac_de_pot = models.FloatField("factor de potencia",default=0.0)
    pot_activa = models.FloatField("Potencia activa",default=0.0)
    pot_real = models.FloatField("Potencia real",default=0.0)
    pot_aparente = models.FloatField("Potencia aparente",default=0.0)
    flag = models.BooleanField("Estado", default=True)
    date = models.DateTimeField("Fecha de registro",auto_now_add=True)

    room_node = models.ForeignKey(Room_Node, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-date']

entrena/forms.py
from django.forms import ModelForm, HiddenInput
from .models import Node, Room, Room_Node, Reg_Node

class NodeForm(ModelForm):
    class Meta():
        model = Node
        fields = ['tipo_nodo']

class RoomForm(ModelForm):
    class Meta():
        model = Room
        fields = ['nombre_hab']

class RoomNodeForm(ModelForm):
    class Meta():
        model = Room_Node
        fields = '__all__'
        widgets = {
            'room': HiddenInput(),
        }

class RegNodeForm(ModelForm):
    class Meta():
        model = Reg_Node
        fields = '__all__'

api/views.py
from django.shortcuts import get_object_or_404, get_list_or_404
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView

from entrena.models import Reg_Node
from .serializers import RegNodeSerializer

from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from datetime import date, timedelta
from django.utils import timezone

class GetNodeView(generics.RetrieveAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    serializer_class = RegNodeSerializer
    queryset = Reg_Node.objects.all()
    
    def get_object(self, **kwargs):
        queryset = self.get_queryset()
        
        objs = get_list_or_404(queryset, room_node=self.kwargs['room_node'])
        if "notfound" not in queryset:
            return objs[0]
        return objs

class GetNodeAllView(APIView):
    authentication_classes = [TokenAuthentication]

    def get(self, request, format=None, **kwargs):

        end_date = timezone.now()
        start_date = end_date - timedelta(days=14)
        reg_sensors = Reg_Node.objects.filter(room_node=self.kwargs['room_node'], date__range=[start_date, end_date]).order_by('date')
        
        data = {
            'voltaje': [reg.voltaje for reg in reg_sensors],
            'corriente':[reg.corriente for reg in reg_sensors],
            'fac_de_pot':[reg.fac_de_pot for reg in reg_sensors],
            'pot_activa':[reg.pot_activa for reg in reg_sensors],
            'pot_real':[reg.pot_real for reg in reg_sensors],
            'pot_aparente':[reg.pot_aparente for reg in reg_sensors],
            'date':[reg.date for reg in reg_sensors]
        }
        return Response(data)

class SetNodeView(generics.ListCreateAPIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    queryset = Reg_Node.objects.all()
    serializer_class = RegNodeSerializer

entrena/views.py
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import get_object_or_404

from .models import Node, Room, Room_Node, Reg_Node
from .forms import NodeForm, RoomForm, RoomNodeForm, RegNodeForm

def get_vebose_names(model):
    fields = []

    for field in model._meta.fields:
        fields.append(field.verbose_name)

    return fields

class Index(TemplateView):
    template_name = 'entrena/index.html'

class NodeList(CreateView):
    form_class = NodeForm
    # success_url = 'node/list.html'
    template_name = 'entrena/node/list.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['node_list'] = Node.objects.all()

        return context

class RoomList(CreateView):
    form_class = RoomForm
    template_name = 'entrena/room/list.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['room_list'] = Room.objects.all()

        return context

class RoomNodeList(CreateView):
    form_class = RoomNodeForm
    template_name = 'entrena/room_node/list.html'

    def get_initial(self, **kwargs):
        room = get_object_or_404(Room, pk=self.kwargs['pk'])
        return {
            'room': room,
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        fields = get_vebose_names(Room_Node)

        context['fields'] = fields
        context['room'  ] = get_object_or_404(Room, pk=self.kwargs['pk'])
        context['room_node_list'] = Room_Node.objects.filter(room=self.kwargs['pk'])

        return context

class RegNodeList(ListView):
    template_name = 'entrena/reg_node/list.html'

    def get_queryset(self, **kwargs):
        return Reg_Node.objects.filter(room_node=self.kwargs['pk_node'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        fields = get_vebose_names(Reg_Node)
        context['fields'] = fields
        context['node'] = get_object_or_404(Room_Node, pk=self.kwargs['pk_node'])
        context['room'] = get_object_or_404(Room, pk=self.kwargs['pk_room'])
        
        return context

entrena/templates/entrena/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://chartjs.org/dist/2.9.3/Chart.min.js"></script>
    <script src="https://www.chartjs.org/samples/latest/utils.js"></script>
    {% load bootstrap4 %}
    {% bootstrap_css %}

    <title>{% block title %} ENTRENA {% endblock %}</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4 fixed-top">
        <div class="container">
            <a href="{% url 'vistas:home' %}" class="navbar-brand">Entrena</a>

            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a href="{% url 'vistas:home' %}" class="nav-link">Home</a>
                    </li>
                    </li>
                    <li class="nav-item active">
                            <a href="{% url 'vistas:lista_rooms' %}" class="nav-link">Habitaciones</a>
                    </li>
                    <li class="nav-item active">
                            <a href="{% url 'vistas:lista_nodes' %}" class="nav-link">Nodos</a>
                    </li>
                </ul>
            </div>            
            <div class="text-white">{% now "DATE_FORMAT" %}</div>
        </div>
    </nav>
    <div class="container" style="margin-top:80px;">
        {% block content %}
        {% endblock %}              
    </div>

    <footer class="fixed-bottom">
        {% block footer %}
        {% endblock %}
    </footer>

    <script>
        $(document).ready(function() {
            {% block jquery %}{% endblock %}
        })
    </script>

</body>
</html>

entrena/templates/entrena/index.html
{% extends './base.html' %}

{% block content %}
    <h1>Bienvenido</h1>
{% endblock %}

entrena/templates/entrena/node/list.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="col-6">
        <h2>Nodos</h2>
        
        <form class="form" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Agregar" class="btn btn-primary">
        </form>

        <table class="table mt-5">
            <thead class="bg-info">
                <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Tipo de nodo</th>
                </tr>
            </thead>
            <tbody>
                {% for node in node_list %}
                    <tr>
                        <td>{{ node.id }}</td>
                        <td>{{ node.tipo_nodo }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

entrena/templates/entrena/reg_node/list.html
{% extends '../base.html' %}

<script>
{% block jquery %}

var endpoint = '/api/v1/sensores/' + "{{node.id}}" + "/all";

// datos
var voltajes = [];
var corrientes = [];
var fac_de_pots = [];
var pot_activa = [];
var pot_real = [];
var pot_aparente = [];
var dates = [];

$.ajax({
    method: "GET",
    url: endpoint,
    headers: {
        'Authorization': 'Token 7de42a81f4e099395c274698e40fb6b6171070d6'
    },
    success: function(data) {
        voltajes = data.voltaje
        corrientes = data.corriente
        fac_de_pots = data.fac_de_pot
        pot_activa = data.pot_activa
        pot_real = data.pot_real
        pot_aparente = data.pot_aparente
        dates = data.date
        setChart()
    },
    error: function(error_data) {
        console.log(error_data)
    }
});

function setChart(){
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: dates,
            datasets: [{
                label: 'voltaje',
                fill: false,
                backgroundColor: 'rgba(255, 0, 0, 1)',
                data: voltajes,
                borderColor: [
                    'rgba(255, 0, 0, 1)',
                ]
            },
            {
                label: 'corriente',
                fill: false,
                backgroundColor: 'rgba(0, 0, 255, 1)',
                data: corrientes,
                borderColor: [
                    'rgba(0, 0, 255, 1)',
                ]
            },
            {
                label: 'fac. de pot.',
                fill: false,
                backgroundColor: 'rgba(150, 150, 150, 1)',
                data: fac_de_pots,
                borderColor: [
                    'rgba(150, 150, 150, 1)',
                ]
            },
            {
                label: 'pot. activa',
                fill: false,
                backgroundColor: 'rgba(100, 0, 100, 1)',
                data: pot_activa,
                borderColor: [
                    'rgba(100, 0, 100, 1)',
                ]
            },
            {
                label: 'pot. real',
                fill: false,
                backgroundColor: 'rgba(255, 20, 100, 1)',
                data: pot_real,
                borderColor: [
                    'rgba(255, 20, 100, 1)',
                ]
            },
            {
                label: 'pot. aparente',
                fill: false,
                backgroundColor: 'rgba(80, 80, 80, 1)',
                data: pot_aparente,
                borderColor: [
                    'rgba(80, 80, 80, 1)',
                ]
            }]            
        },
        options: {
            responsive: true,
            title: {
                display: true,
                text: 'Registros'
            },
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: false,
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'values'
                    },
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
}
// ************************************************************************

{% endblock %}
</script>

{% block content %}

    <div class="col-12">
        <h2>{{ room }} - {{ node.node }} ({{ node.id }}) - Registros</h2>

        <canvas id="myChart" width="400" height="190" class="chartjs-render-monitor"></canvas>

    </div>

{% endblock %}

entrena/templates/entrena/room/list.html
{% extends '../base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="col-6">
        <h2>Habitaciones</h2>
    
        <form class="form" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Agregar" class="btn btn-primary">
        </form>

        <table class="table mt-5">
            <thead class="bg-info">
                <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nombre de habitación</th>
                        <th scope="col">Ver</th>
                </tr>
            </thead>
            <tbody>
                {% for room in room_list %}
                    <tr>
                        <td>{{ room.id }}</td>
                        <td>{{ room.nombre_hab }}</td>
                        <td><a href="{% url 'vistas:lista_room_node' room.id %}">Nodos</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

entrena/templates/entrena/room_node/list.html
{% extends '../base.html' %}

<!-- {% load crispy_forms_tags %} -->

{% block content %}

    <div class="col-6">
        <h2>{{ room }} - Nodos</h2>
        
        <form class="form" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Agregar" class="btn btn-primary">
        </form>

        <table class="table mt-5">
            <thead class="bg-info">
                <tr>
                    {% for field in fields %}
                        {% if field != "room" %}
                            <th scope="col">{{ field }}</th>
                        {% endif %}
                    {% endfor %}
                    <th>Ver</th>
                </tr>
            </thead>
            <tbody>
                {% for node in room_node_list %}
                    <tr>
                        <td>{{ node.id }}</td>
                        <td>{{ node.node }}</td>
                        <td><a href="{% url 'vistas:lista_reg_node' room.id node.id %}">Registros</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}